/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Registros;

import Logic.Factura;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;


/**
 *
 * @author boyro
 * 
 */
public class View extends javax.swing.JDialog implements Observer {

    /**
     * Creates new form View
     */
    
    private Controller control;
    private Model model;
    public View(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Volver = new javax.swing.JButton();
        Cancelarr = new javax.swing.JButton();
        generarPDFBttn = new javax.swing.JButton();
        generarXMLBttn = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        GuardarBttn = new javax.swing.JButton();
        lineaFacturaPresentadaTxtFld = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableDeFacturas = new javax.swing.JTable();

        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        Volver.setBackground(new java.awt.Color(0, 153, 153));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-25.png"))); // NOI18N
        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        Cancelarr.setBackground(new java.awt.Color(0, 153, 153));
        Cancelarr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Cancelarr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        Cancelarr.setText("Cancelar");
        Cancelarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarrActionPerformed(evt);
            }
        });

        generarPDFBttn.setText("Generar PDF");
        generarPDFBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarPDFBttnMouseClicked(evt);
            }
        });
        generarPDFBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPDFBttnActionPerformed(evt);
            }
        });

        generarXMLBttn.setText("Generar XML");
        generarXMLBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarXMLBttnMouseClicked(evt);
            }
        });

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-new-copy-20.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        GuardarBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon-icons.com_53618.png"))); // NOI18N
        GuardarBttn.setText("Guardar");
        GuardarBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarBttnMouseClicked(evt);
            }
        });
        GuardarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBttnActionPerformed(evt);
            }
        });

        lineaFacturaPresentadaTxtFld.setBackground(new java.awt.Color(204, 204, 255));

        TableDeFacturas.setBackground(new java.awt.Color(255, 153, 153));
        TableDeFacturas.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        TableDeFacturas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableDeFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "# Factura", "Cliente", "SubTotal", "IVA"
            }
        ));
        TableDeFacturas.setColumnSelectionAllowed(true);
        TableDeFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDeFacturasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableDeFacturas);
        TableDeFacturas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(GuardarBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generarXMLBttn)
                .addGap(26, 26, 26)
                .addComponent(generarPDFBttn)
                .addGap(28, 28, 28)
                .addComponent(Cancelarr)
                .addGap(18, 18, 18)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lineaFacturaPresentadaTxtFld))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lineaFacturaPresentadaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelarr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarPDFBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarXMLBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        control.hide();
    }//GEN-LAST:event_VolverMouseClicked

    private void GuardarBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBttnMouseClicked
        try {
            JOptionPane.showMessageDialog(null, "Metodo incompleto hay que decidir que guardar.....");
           // Logic.Service.getInstance().Save("Facturas.xml");//change root name
        } catch (Exception ex) {
            System.out.println(ex.getCause());
        }  

    }//GEN-LAST:event_GuardarBttnMouseClicked

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
       
        limpiarTextField();
        
    }//GEN-LAST:event_nuevoActionPerformed

    private void CancelarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarrActionPerformed
      
      limpiarTextField();
    }//GEN-LAST:event_CancelarrActionPerformed

    private void GuardarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBttnActionPerformed
       // JOptionPane.showMessageDialog(null, "Sin Implementar");
    }//GEN-LAST:event_GuardarBttnActionPerformed

    private void generarPDFBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPDFBttnActionPerformed
      //  JOptionPane.showMessageDialog(null, "Sin Implementar");
//         try {
//            Factura FacturaElectronica = model.getFactura();
//            Logic.Service.getInstance().makeFacturaXML(FacturaElectronica);
//        } catch (Exception ex) {
//            System.out.println(ex.getCause());
//        }
    }//GEN-LAST:event_generarPDFBttnActionPerformed

    private void generarXMLBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarXMLBttnMouseClicked
        try {
            Factura FacturaElectronica = model.getFactura();
            Logic.Service.getInstance().makeFacturaXML(FacturaElectronica);
        } catch (Exception ex) {
            System.out.println(ex.getCause());
            JOptionPane.showMessageDialog(null, "No fue posible crear el XML");
        }
    }//GEN-LAST:event_generarXMLBttnMouseClicked

    private void generarPDFBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarPDFBttnMouseClicked
        //JOptionPane.showMessageDialog(null, "Sin Implementar");
         try {
            Factura FacturaElectronica = model.getFactura();
            Logic.Service.getInstance().createPDF(FacturaElectronica);
        } catch (Exception ex) {
            System.out.println(ex.getCause());
            JOptionPane.showMessageDialog(null, "No fue posible crear el PDF");
        }
    }//GEN-LAST:event_generarPDFBttnMouseClicked

    private void TableDeFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDeFacturasMouseClicked
            int selectedFactura = this.TableDeFacturas.getSelectedRow();
             if (selectedFactura> -1) {
                this.control.setFactura(selectedFactura);
                this.lineaFacturaPresentadaTxtFld .setText(model.getFactura().getNumeroFactura());
            this.lineaFacturaPresentadaTxtFld.setEditable(false);
            this.lineaFacturaPresentadaTxtFld.setEnabled(false);
            }
        
    }//GEN-LAST:event_TableDeFacturasMouseClicked

    
    @Override
    public void update(Observable o, Object arg) {
       this.TableDeFacturas.setModel(model.getTable());
    }

    public Controller getControl() {
        return control;
    }

    public void setControl(Controller control) {
        this.control = control;
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelarr;
    private javax.swing.JButton GuardarBttn;
    private javax.swing.JTable TableDeFacturas;
    private javax.swing.JButton Volver;
    private javax.swing.JButton generarPDFBttn;
    private javax.swing.JButton generarXMLBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lineaFacturaPresentadaTxtFld;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables

    private void limpiarTextField() {
           this.lineaFacturaPresentadaTxtFld .setText("");
           this.lineaFacturaPresentadaTxtFld.setEditable(true);
           this.lineaFacturaPresentadaTxtFld.setEnabled(true);
    }

   
}

